### ISSUE TITLE
Rework resource handling for cwltool>=3.0.20200317142916

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#116]
Checkout the issue I described in https://github.com/galaxyproject/galaxy/pull/10658.

**Comment by mr-c** [comment]
cwltool 3.0.20201109103151 has been released with a fix for this

**Comment by jmchilton** [comment]
Amazing, thanks so much.

**Comment by mr-c** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/10658 !
