### ISSUE TITLE
Migrate Travis Tests to Github Actions

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#121]
Fix them also - but that is another thing 😆. Also maybe environments for targeting CWL 1.0, 1.1, 1.2

**Comment by nsoranzo** [comment]
As mentioned, I can work on this, I am working on the Travis -> GH migration for starforge-recipes right now!

**Comment by nsoranzo** [comment]
Fixed in https://github.com/common-workflow-language/galaxy/pull/132
