### ISSUE TITLE
Port ``when`` (conditonal) handling back into core + ga/format2

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#131]
I think just adding when to the formats is easy. I think extracting some of that expression evaluation stuff out will be really valuable in terms of getting more CWL branch into Galaxy. I'm thinking about what it would look like in terms of Galaxy though - particularly through the filter for Format 2 right now, but the workflow editor is relatively easy with this implementation of conditional processing.

So the way it works is you can attach a ``when`` expression on a workflow step and if it doesn't evaluate to ``True``, all the outputs will simply be replaced with ``null`` and the step will be skipped. This doesn't break anything really in Galaxy, but to make the format2 examples look useful/interesting and to make it useful in the workflow editor - I'm thinking it would be worth implementing an expression tool for Galaxy for picking branches of computation essentially.

It would be modeled off the type dispatching and conditional outputs of param_value_from_file. It would each allow a selection of ``param_type`` the same way and then it would have a repeat based on that. The repeat would take in parameters of the specified type - and depending on another flag return either the first non-null input from the repeat or return the only matching non-null value (failing if multiple non_nulls are found).

**Comment by mvdbeek** [comment]
All done and ported back now, will be part of 23.0
