### ISSUE TITLE
Enhance the Python typing for the files we touch 

### ISSUE THREAD

**Issue by mr-c** [common-workflow-lab/galaxy#137]
1. Find a Python file we touch in ~~https://github.com/common-workflow-lab/galaxy/pull/47~~ https://github.com/galaxyproject/galaxy/pull/12909 or https://github.com/common-workflow-language/galaxy/pull/123
2. Edit https://github.com/galaxyproject/galaxy/blob/dev/setup.cfg#L24 to remove the `check_untyped_defs = False` from underneath that filename
3. `tox -e mypy`
4. Fix/enhance types ; send PR to https://github.com/galaxyproject/galaxy/ against the `dev` branch
5. Repeat from 1 with another file

- [x] `lib/galaxy/config/__init__.py`
- [x] `lib/galaxy/datatypes/data.py`
- [x] `lib/galaxy/job_execution/output_collect.py`
- [x] `lib/galaxy/jobs/__init__.py`
- [x] `lib/galaxy/jobs/command_factory.py`
- [x] `lib/galaxy/jobs/runners/local.py`
- [x] `lib/galaxy/managers/collections.py`
- [x] `lib/galaxy/managers/collections_util.py`
- [x] `lib/galaxy/managers/histories.py`
- [x] `lib/galaxy/managers/tools.py`
- [x] `lib/galaxy/managers/workflows.py`
- [x] `lib/galaxy/metadata/__init__.py`
- [x] `lib/galaxy/model/__init__.py`
- [x] `lib/galaxy/model/dataset_collections/builder.py`
- [x] `lib/galaxy/model/dataset_collections/matching.py`
- [x] `lib/galaxy/model/dataset_collections/registry.py`
- [x] `lib/galaxy/model/dataset_collections/type_description.py`
- [x] `lib/galaxy/model/dataset_collections/types/__init__.py`
- [x] `lib/galaxy/model/dataset_collections/types/list.py`
- [x] `lib/galaxy/model/dataset_collections/types/paired.py`
- [x] `lib/galaxy/schema/schema.py`
- [x] `lib/galaxy/tool_util/client/staging.py`
- [x] `lib/galaxy/tool_util/cwl/parser.py`
- [x] `lib/galaxy/tool_util/cwl/representation.py`
- [x] `lib/galaxy/tool_util/cwl/schema.py`
- [x] `lib/galaxy/tool_util/cwl/util.py`
- [x] `lib/galaxy/tool_util/output_checker.py`
- [x] `lib/galaxy/tool_util/parser/cwl.py`
- [x] `lib/galaxy/tool_util/parser/factory.py`
- [x] `lib/galaxy/tool_util/parser/interface.py`
- [x] `lib/galaxy/tool_util/parser/output_objects.py`
- [x] `lib/galaxy/tool_util/parser/yaml.py`
- [x] `lib/galaxy/tools/__init__.py`
- [x] `lib/galaxy/tools/actions/__init__.py`
- [x] `lib/galaxy/tools/evaluation.py`
- [x] `lib/galaxy/tools/execute.py`
- [x] `lib/galaxy/tools/parameters/basic.py`
- [x] `lib/galaxy/tools/parameters/grouping.py`
- [x] `lib/galaxy/tools/parameters/wrapped.py`
- [x] `lib/galaxy/tools/wrappers.py`
- [x] `lib/galaxy/util/compression_utils.py`
- [x] `lib/galaxy/webapps/galaxy/api/tools.py`
- [x] `lib/galaxy/webapps/galaxy/api/workflows.py`
- [x] `lib/galaxy/webapps/galaxy/controllers/tool_runner.py`
- [x] `lib/galaxy/webapps/galaxy/services/dataset_collections.py`
- [x] `lib/galaxy/workflow/modules.py`
- [x] `lib/galaxy/workflow/run.py`
- [x] `lib/galaxy/workflow/run_request.py`
- [x] `lib/galaxy/workflow/steps.py`
- [x] `lib/galaxy_test/api/test_dataset_collections.py`
- [x] `lib/galaxy_test/api/test_tools.py`
- [x] `lib/galaxy_test/driver/driver_util.py`
- [x] `test/integration/test_upload_configuration_options.py`
- [x] `test/unit/app/jobs/test_command_factory.py`
- [x] `test/unit/app/jobs/test_runner_local.py`
- [x] `test/unit/app/managers/test_HistoryManager.py`
- [x] `test/unit/tool_util/test_parsing.py`

**Comment by mr-c** [comment]
I've assigned myself, but others are welcome as well

**Comment by dakariakin** [comment]
Started work in https://github.com/dakariakin/galaxy/commits/added_types
- [x] lib/galaxy/model/dataset_collections/registry.py
- [x] lib/galaxy/model/dataset_collections/matching.py (need to discuss)
- [x] lib/galaxy/job_execution/output_collect.py

**Comment by dakariakin** [comment]
Sent WIP PR https://github.com/galaxyproject/galaxy/pull/12884
Will continue with
- [x] `lib/galaxy/jobs/__init__.py`
- [x] `lib/galaxy/jobs/runners/local.py`

**Comment by mr-c** [comment]
Tomorrow I plan on working on 

- [x] `lib/galaxy/tools/__init__.py`
- [x] `lib/galaxy/tools/actions/__init__.py`
- [x] `lib/galaxy/tools/evaluation.py`
- [x] `lib/galaxy/tools/execute.py`
- [x] `lib/galaxy/tools/parameters/basic.py`
- [x] `lib/galaxy/tools/parameters/grouping.py`

**Comment by dakariakin** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/12884
- [x] lib/galaxy/tool_util/client/staging.py
- [x] lib/galaxy/tool_util/output_checker.py

Tomorrow I'll work on
- [x] lib/galaxy/tool_util/cwl/parser.py
- [x] lib/galaxy/tool_util/cwl/representation.py

**Comment by mr-c** [comment]
Next up for me: 
- [x] `lib/galaxy/managers/collections.py`
- [x] `lib/galaxy/managers/collections_util.py`
- [x] `lib/galaxy/managers/tools.py`
- [x] `lib/galaxy/managers/workflows.py`

**Comment by dakariakin** [comment]
also done with
- [x] `lib/galaxy/tool_util/parser/yaml.py`
- [x] `lib/galaxy/tool_util/parser/output_objects.py`
- [x] `lib/galaxy/metadata/__init__.py`

I'll work on  `lib/galaxy/model/__init__.py` on separate PR because it throws 119 errors

**Comment by mr-c** [comment]
Building off of @dakariakin 's https://github.com/galaxyproject/galaxy/pull/12884/ I will work on the following next:

- [x] `lib/galaxy/tool_util/client/staging.py`
- [x] `lib/galaxy/tool_util/cwl/parser.py`
- [x] `lib/galaxy/tool_util/cwl/representation.py`
- [x] `lib/galaxy/tool_util/output_checker.py`
- [x] `lib/galaxy/tool_util/parser/cwl.py`

**Comment by mr-c** [comment]
I updated the list at the top, and I'll be working on the new entries from the bottom up

**Comment by dakariakin** [comment]
I've just created an MR with typings for lib/galaxy/model/__init__.py
https://github.com/galaxyproject/galaxy/pull/12971

Could you please review it?
