### ISSUE TITLE
Implement checking of CWL Version when loading tools.

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#16]
Don't load unsupported tools.

**Comment by tetron** [comment]
FYI cwltool automatically up-converts when using load_tool().

**Comment by jmchilton** [comment]
Which is great, I guess this issue is more about making sure if an older Galaxy has an older cwltool dependency it doesn't try to load newer tools.

**Comment by jmchilton** [comment]
Also - I really don't want Galaxy to be able to run older CWL tools - it should only run draft3+ unless draft4 also removes something difficult to support long term (draft 3 remove arbitrary expressions). Once Galaxy runs something (out of the box anyway) - it should always be able to run it.

**Comment by jmchilton** [comment]
I think I did this - but there should be a test case to verify this.
