### ISSUE TITLE
Implement Python 3.4/5 support for cwltool

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#18]

**Comment by mr-c** [comment]
I will also do this.

**Comment by jmchilton** [comment]
Awesome, thanks for volunteering @mr-c!

**Comment by jmchilton** [comment]
Yay - it has been merged thanks to https://github.com/common-workflow-language/cwltool/pull/442 - ready to add universal instead of conditional dependency on cwltool in Planemo.
