### ISSUE TITLE
Implement Python 2.6 support for schema salad.

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#19]

**Comment by mr-c** [comment]
O RLY?

**Comment by mr-c** [comment]
@jmchilton Is Py2.6 support really needed? I was going to convert to idiomatic Python 3 with Python 2.7 compatibility; Adding Py2.6 compatibility makes that tricky.

**Comment by jmchilton** [comment]
Depends I guess on the ETA for getting this into Galaxy. We will drop support for 2.6 someday -  I don't know if it will be this year though. What exactly is idiomatic Python 3 that 2.7 allows but not 2.6? I've done this a few times and it always just seems to be dictionary comprehensions and library support that can be obtained via dependencies, but maybe because I write Python 3 compatible Python 2.7 instead of the inverse.

I put the Python 3 issues here for planemo and maybe pulsar to leverage cwltool, for getting this into Galaxy in the first half of 2016 Python 2.6 is much more important however. I'm happy to take a long view on this if you wish, especially if @tetron would prefer to avoid supporting 2.6.

**Comment by mr-c** [comment]
Thanks for the explanation. Py3 support is required for adding to Debian; I
will document any Py2.6 issues I run into here.
