### ISSUE TITLE
Rework Docker run - at least when no base command is specified.

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#66]
Well apparently base command can be empty and Docker's command (``CMD``) is assumed in that case. This seems like a fairly big issue since this isn't how Galaxy executed Docker commands:

> The platform must execute the tool in the container using docker run with the appropriate Docker image and tool command line.

**Comment by tetron** [comment]
That's not what was intended.  The idea was that it should always control the command that is run inside the container.  I'm curious anyone is actually relying on this behavior.

**Comment by jmchilton** [comment]
@tetron One of the GA4GH workflows uses this pattern extensively. 😢

**Comment by tetron** [comment]
Huh.  Which one?

**Comment by jmchilton** [comment]
- https://github.com/ENCODE-DCC/pipeline-container/blob/master/local-workflows/mapping.cwl
- https://github.com/ENCODE-DCC/pipeline-container/blob/master/local-workflows/xcor.cwl

**Comment by tetron** [comment]
It looks to me like it still is passing command line parameters, so CMD is ignored, but what does happen is that it invokes ENTRYPOINT with those parameters.  Yay Docker!

**Comment by jmchilton** [comment]
Yeah - I probably confused CMD and ENTRYPOINT. I take this entrypoint behavior was intended?

**Comment by tetron** [comment]
Ehhhhh... it would be fair to say the interaction between DockerRequirement and ENTRYPOINT was not fully thought out.

**Comment by tetron** [comment]
At the very least, anything relying on this behavior should have DockerRequirement in the `requirements` section, and not just `hints`.

**Comment by jmchilton** [comment]
I've implemented this change - it is less terrible than I feared so far. https://github.com/common-workflow-language/galaxy/pull/47/commits/14ef8ca0b3a58f6f22e1b150967641f71abd7406
